[package]
name = "abc"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.100"
argon2 = { version = "0.5.3", features = ["std"] }
jsonrpsee = { version = "0.26.0", features = ["server"] }
secp256k1 = { version = "0.31.1", features = [
  "global-context",
  "hashes",
  "rand",
  "std"
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10.8"
tokio = { version = "1.48.0", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }

[dev-dependencies]
proptest = "1.9.0"
tempfile = "3.10.1"
